name: ROS 2 CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: nanosaur_gazebo
        target-ros2-distro: humble
